spring:
  application:
    name: cloud-eureka #hope-plus-cloud 服务注册中心
server:
  port: 8763
eureka:
  instance:
    hostname: cloud-eureka63 #主机名
  server:
    enable-self-preservation: true #关闭自我保护机制，防止失效的服务也被一直访问 （开发环境建议关闭 false)
    eviction-interval-timer-in-ms: 5000 #该配置可以修改检查失效服务的时间，每隔5s检查失效服务，默认该配置是 60s （开发环境)
  client:
      register-with-eureka: true
      fetch-registry: true
    serviceUrl:
      defaultZone: http://cloud-eureka62:8762/eureka/,http://cloud-eureka61:8761/eureka/

